# Generated by Django 4.0.3 on 2022-07-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('comissao', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Habilitacao',
            fields=[
                ('numeroHab', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('validadeHab', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TelefoneCorretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=20)),
                ('cpfCorretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ListaWeb2Tri.corretor')),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('IdMunicipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ListaWeb2Tri.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('CartHab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ListaWeb2Tri.habilitacao')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('matricula', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('codigodep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ListaWeb2Tri.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='CorGerCor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpfGerenciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gerenciado', to='ListaWeb2Tri.corretor')),
                ('cpfGerenciador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Gerenciador', to='ListaWeb2Tri.corretor')),
            ],
        ),
        migrations.CreateModel(
            name='CorAtendeReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdRegiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ListaWeb2Tri.regiao')),
                ('cpfCorretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ListaWeb2Tri.corretor')),
            ],
        ),
    ]
