# Generated by Django 4.0.5 on 2022-10-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListaWeb2Tri', '0003_remove_corgercor_cpfgerenciado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corgercor',
            name='corretores',
            field=models.ManyToManyField(to='ListaWeb2Tri.corretor'),
        ),
    ]
