# Generated by Django 3.2.15 on 2022-10-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ListaWeb2Tri', '0005_corretor_corretores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorGerCor',
        ),
    ]
